Implement logic for GQ person moves
ihmeuw/vivarium_census_prl_synth_pop pull request #104
Opened 2022-12-19 22:36 UTC by zmbc

## Implement logic for GQ person moves

### Description

- *Category*: implementation
- *JIRA issue*: [MIC-3674](https://jira.ihme.washington.edu/browse/MIC-3674)
- *Research reference*: https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#gq-person-moves

### Changes and notes

I did the sampling of GQ type in the opposite order to what I wrote in the ticket: first choose the GQ housing type category (institutional or non-institutional) then choose the specific housing type (carceral, nursing home, etc). This will be easier to upgrade if we go on to implement a correlation between demographics and GQ housing type category.

### Verification and Testing

Ran simulation, stepped through and verified sims were moving to GQ and had correct address IDs and housing types.

2022-12-19 23:23 UTC, zmbc commented
I seem to have found a bug with this; am investigating.

2022-12-20 01:36 UTC, rmudambi requested changes

2022-12-20 01:36 UTC, rmudambi commented on src/vivarium_census_prl_synth_pop/components/person.py
> +        housing_type_category_values = self.randomness.choice(
Doesn't this move them with equal probability to institutional or non-institutional GQ? We have a bunch of data for moving into GQ that I don't see used here. Has something changed in the model?

2022-12-20 01:36 UTC, rmudambi commented on src/vivarium_census_prl_synth_pop/components/person.py
> +                choices=list(housing_types.values()),
Same comment as above.

2022-12-20 20:34 UTC, rmudambi approved these changes

2022-12-20 21:07 UTC, merged