floor age and enforce zipcode as int
ihmeuw/vivarium_census_prl_synth_pop pull request #253
Opened 2023-03-28 23:47 UTC by stevebachmeier

## Title: Floor age and set zipcodes as int

### Description
- *Category*: bugfix 
- *JIRA issue*: [MIC-3932](https://jira.ihme.washington.edu/browse/MIC-3932)
- *Research reference*: na

### Changes and notes
This PR does two simple things. When post-processing:
- Force zipcodes to be integers (currently they are floats)
- Modify the "real" age (which is a floag, eg 39.384623) to int (eg 39)

### Verification and Testing
tests pass

2023-03-28 23:53 UTC, rmudambi requested changes

2023-03-28 23:53 UTC, rmudambi commented on src/vivarium_census_prl_synth_pop/tools/make_results.py
> +                if "age" in df.columns:
The proper way to do this is to add a formatter to the age column that gets called by `formatter.format_columns()`

2023-03-28 23:55 UTC, rmudambi commented on src/vivarium_census_prl_synth_pop/results_processing/addresses.py
> +    zip_map = pd.Series(-1, index=simulation_addresses.index, dtype=int)
How do we handle zipcodes that start with 0?

2023-03-29 00:04 UTC, aflaxman commented
Thank you!

2023-03-29 23:54 UTC, merged