Select individual movers of each type using rates
ihmeuw/vivarium_census_prl_synth_pop pull request #94
Opened 2022-12-14 21:03 UTC by zmbc

## Select individual movers of each type using rates

### Description

- *Category*: implementation
- *JIRA issue*: [MIC-3672](https://jira.ihme.washington.edu/browse/MIC-3672)
- *Research reference*: https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#individual-moves

### Changes and notes

Unlike what I originally wrote in the ticket, I have made it so that _all_ move types are passed onto the old moving logic (for now), not only non-reference person movers. Seemed to make more sense because the old move logic encapsulated both non-reference person and GQ person moves.

I believe when we get to immigration/emigration, we will want to rename this component to make it clear that it is only about domestic migration.

### Verification and Testing

Ran simulation without error; stepped through code to check that reasonable numbers of people were moving.

2022-12-14 21:47 UTC, rmudambi requested changes
Mostly looks good. One comment about doing some things on each time-step that should be done only once in the setup phase.

2022-12-14 21:47 UTC, rmudambi commented on src/vivarium_census_prl_synth_pop/components/person.py
> +        move_type_probabilities = (
Don't rename columns here. There's no reason why `self.person_move_rates()` shouldn't return a DataFrame which already has the correct column names. Either fix the backing csv or set the column names properly in `setup` before setting it as the backing data of the `LookupTable`. 

The residual choice column should also be created in setup

2022-12-14 21:51 UTC, albrja commented on src/vivarium_census_prl_synth_pop/components/person.py
>          persons = self.population_view.get(event.index)
Can you change this to just pop or population?  The naming is old and that keeps it clear and consistent across components.  I'm updating this in the other components.

2022-12-14 21:51 UTC, albrja approved these changes
Looks good with a nit.

2022-12-16 00:38 UTC, rmudambi approved these changes
Approved pending the changes we talked about.

2022-12-16 18:30 UTC, merged